# Generated by Django 5.2.17 on 2026-08-28 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_monthly_assembly",
            field=models.BooleanField(
                default=False, verbose_name="Assemblée mensuelle"
            ),
        ),
    ]
