# Generated by Django 5.2.17 on 2026-08-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_is_monthly_assembly"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actualite",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="actualites/%Y/%m/",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="eventimage",
            name="image",
            field=models.ImageField(
                max_length=500, upload_to="events/%Y/%m/", verbose_name="Image"
            ),
        ),
    ]
