services:
  - type: web
    name: afe-api
    runtime: python
    plan: free
    region: frankfurt
    branch: deployment
    rootDir: backend
    buildCommand: ./build.sh
    startCommand: gunicorn afe_api.wsgi:application
    healthCheckPath: /healthz/
    autoDeploy: true
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com,afe-agdk.com,www.afe-agdk.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://afe-agdk.com,https://www.afe-agdk.com,https://site-afe.vercel.app,http://localhost:5173"
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
