# Generated by Django 5.2.14 on 2026-08-26 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant"
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[("income", "Recette"), ("expense", "Dépense")],
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Catégorie"
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "receipt",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="accounting/receipts/%Y/%m/",
                        verbose_name="Justificatif",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Enregistrement financier",
                "verbose_name_plural": "Enregistrements financiers",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="MeetingReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("date", models.DateField(verbose_name="Date de la réunion")),
                ("summary", models.TextField(verbose_name="Résumé")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="meetings/%Y/%m/",
                        verbose_name="PV",
                    ),
                ),
                (
                    "visible_to",
                    models.CharField(
                        default="bureau", max_length=20, verbose_name="Visible pour"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meeting_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Compte-rendu de réunion",
                "verbose_name_plural": "Comptes-rendus de réunions",
                "ordering": ["-date"],
            },
        ),
    ]
