# Generated by Django 5.2.17 on 2026-08-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_cotisation_galleryitem_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryitem",
            name="file_type",
            field=models.CharField(
                choices=[("image", "Image"), ("video", "Vidéo")],
                default="image",
                max_length=10,
                verbose_name="Type",
            ),
        ),
        migrations.AddField(
            model_name="galleryitem",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="gallery/videos/%Y/%m/",
                verbose_name="Vidéo",
            ),
        ),
        migrations.AlterField(
            model_name="galleryitem",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="gallery/%Y/%m/", verbose_name="Image"
            ),
        ),
    ]
