# Generated by Django 5.2.17 on 2026-08-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_galleryitem_file_type_galleryitem_video_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryitem",
            name="image_url",
            field=models.URLField(blank=True, verbose_name="URL image externe"),
        ),
        migrations.AddField(
            model_name="galleryitem",
            name="video_platform",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Plateforme vidéo"
            ),
        ),
        migrations.AddField(
            model_name="galleryitem",
            name="video_url",
            field=models.URLField(blank=True, verbose_name="URL vidéo externe"),
        ),
    ]
