# Generated by Django 5.2.17 on 2026-08-27 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounting",
            "0004_galleryitem_image_url_galleryitem_video_platform_and_more",
        ),
        (
            "members",
            "0006_member_account_status_membershipapplication_id_back_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "donor_name",
                    models.CharField(max_length=200, verbose_name="Nom du donateur"),
                ),
                (
                    "donor_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone du donateur"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Méthode"
                    ),
                ),
                (
                    "target_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Numéro de réception"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant"
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Message")),
                (
                    "status",
                    models.CharField(
                        choices=[("received", "Reçu"), ("confirmed", "Confirmé")],
                        default="received",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Don",
                "verbose_name_plural": "Dons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("message", models.TextField(blank=True, verbose_name="Message")),
                ("is_read", models.BooleanField(default=False, verbose_name="Lue")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
