# Generated by Django 5.2.17 on 2026-08-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_donation_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialrecord",
            name="receipt",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="accounting/receipts/%Y/%m/",
                verbose_name="Justificatif",
            ),
        ),
        migrations.AlterField(
            model_name="galleryitem",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="gallery/%Y/%m/",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="galleryitem",
            name="video",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="gallery/videos/%Y/%m/",
                verbose_name="Vidéo",
            ),
        ),
        migrations.AlterField(
            model_name="meetingreport",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="meetings/%Y/%m/",
                verbose_name="PV",
            ),
        ),
    ]
