# Generated by Django 5.2.14 on 2026-08-26 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/%Y/%m/", verbose_name="Fichier"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("report", "Compte-rendu"),
                            ("financial", "Comptabilité"),
                            ("legal", "Officiel"),
                            ("minutes", "Procès-verbal"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "visible_to",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("members", "Membres"),
                            ("bureau", "Bureau"),
                        ],
                        default="members",
                        max_length=20,
                        verbose_name="Visible pour",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-created_at"],
            },
        ),
    ]
