# Generated by Django 5.2.17 on 2026-08-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                max_length=500, upload_to="documents/%Y/%m/", verbose_name="Fichier"
            ),
        ),
    ]
