# Generated by Django 5.2.17 on 2026-09-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_alter_document_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file_data",
            field=models.BinaryField(
                blank=True,
                help_text="Octets du fichier uploadé par le bureau, stockés en base pour survivre aux redéploiements (disque éphémère sur Render). Les documents seed/ n'utilisent que `file` (référence vers seed/).",
                null=True,
                verbose_name="Contenu du fichier",
            ),
        ),
    ]
