# Generated by Django 5.2.14 on 2026-08-26 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Membre"),
                            ("bureau", "Bureau"),
                            ("admin", "Admin"),
                        ],
                        default="member",
                        max_length=20,
                        verbose_name="Rôle",
                    ),
                ),
                (
                    "membership_status",
                    models.BooleanField(
                        default=False, verbose_name="Cotisation à jour"
                    ),
                ),
                (
                    "membership_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'adhésion"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Adresse")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="members/photos/",
                        verbose_name="Photo",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Biographie")),
                (
                    "show_in_directory",
                    models.BooleanField(
                        default=True, verbose_name="Afficher dans l'annuaire"
                    ),
                ),
                (
                    "rgpd_consent",
                    models.BooleanField(
                        default=False, verbose_name="Consentement RGPD"
                    ),
                ),
                (
                    "joined_date",
                    models.DateField(auto_now_add=True, verbose_name="Date de joining"),
                ),
                (
                    "is_active_member",
                    models.BooleanField(default=True, verbose_name="Membre actif"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Membre",
                "verbose_name_plural": "Membres",
                "ordering": ["-joined_date"],
            },
        ),
        migrations.CreateModel(
            name="BureauMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("president", "Président"),
                            ("vice_president", "Vice-Président"),
                            ("secretary", "Secrétaire"),
                            ("treasurer", "Trésorier"),
                            ("member", "Membre du Bureau"),
                        ],
                        max_length=20,
                        verbose_name="Poste",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "mandate_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="Début du mandat"
                    ),
                ),
                (
                    "mandate_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fin du mandat"
                    ),
                ),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bureau_position",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membre du Bureau",
                "verbose_name_plural": "Membres du Bureau",
                "ordering": ["display_order"],
            },
        ),
    ]
