# Generated by Django 5.2.17 on 2026-08-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="role",
            field=models.CharField(
                choices=[
                    ("member", "Membre"),
                    ("bureau", "Bureau"),
                    ("secretary", "Secrétaire"),
                    ("admin", "Admin"),
                ],
                default="member",
                max_length=20,
                verbose_name="Rôle",
            ),
        ),
    ]
