# Generated by Django 5.2.17 on 2026-08-26 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_alter_member_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="role",
            field=models.CharField(
                choices=[
                    ("member", "Membre"),
                    ("bureau", "Bureau"),
                    ("secretary", "Secrétaire"),
                    ("treasurer", "Trésorier"),
                    ("admin", "Admin"),
                ],
                default="member",
                max_length=20,
                verbose_name="Rôle",
            ),
        ),
        migrations.CreateModel(
            name="MembershipApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "demand_letter",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="applications/letters/%Y/%m/",
                        verbose_name="Lettre de demande",
                    ),
                ),
                (
                    "supporting_documents",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="applications/documents/%Y/%m/",
                        verbose_name="Documents justificatifs",
                    ),
                ),
                ("motivation", models.TextField(blank=True, verbose_name="Motivation")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Approuvée"),
                            ("rejected", "Rejetée"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "review_note",
                    models.TextField(blank=True, verbose_name="Note du bureau"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidature d'adhésion",
                "verbose_name_plural": "Candidatures d'adhésion",
                "ordering": ["-created_at"],
            },
        ),
    ]
