# Generated by Django 5.2.17 on 2026-08-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_alter_member_role_membershipapplication"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssociationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "collective_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="members/collective/",
                        verbose_name="Photo collective",
                    ),
                ),
                (
                    "cover_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="cover/",
                        verbose_name="Photo de couverture",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Paramètres de l'association",
                "verbose_name_plural": "Paramètres de l'association",
            },
        ),
    ]
