# Generated by Django 5.2.17 on 2026-08-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_associationsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bureaumember",
            name="position",
            field=models.CharField(
                choices=[
                    ("president", "Président"),
                    ("vice_president", "Vice-Président"),
                    ("secretary", "Secrétaire"),
                    ("treasurer", "Trésorier"),
                    ("member", "Conseiller"),
                ],
                max_length=20,
                verbose_name="Poste",
            ),
        ),
    ]
