# Generated by Django 5.2.17 on 2026-08-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_alter_bureaumember_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("active", "Actif"),
                    ("suspended", "Suspendu"),
                    ("deactivated", "Désactivé"),
                ],
                default="active",
                max_length=20,
                verbose_name="Statut du compte",
            ),
        ),
        migrations.AddField(
            model_name="membershipapplication",
            name="id_back",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="applications/id/%Y/%m/",
                verbose_name="Pièce d'identité (verso)",
            ),
        ),
        migrations.AddField(
            model_name="membershipapplication",
            name="id_front",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="applications/id/%Y/%m/",
                verbose_name="Pièce d'identité (recto)",
            ),
        ),
        migrations.AddField(
            model_name="membershipapplication",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="applications/photos/%Y/%m/",
                verbose_name="Photo passeport",
            ),
        ),
    ]
