# Generated by Django 5.2.17 on 2026-08-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "members",
            "0006_member_account_status_membershipapplication_id_back_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="associationsettings",
            name="collective_photo",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="members/collective/",
                verbose_name="Photo collective",
            ),
        ),
        migrations.AlterField(
            model_name="associationsettings",
            name="cover_photo",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="cover/",
                verbose_name="Photo de couverture",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="photo",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="members/photos/",
                verbose_name="Photo",
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="demand_letter",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="applications/letters/%Y/%m/",
                verbose_name="Lettre de demande",
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="id_back",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="applications/id/%Y/%m/",
                verbose_name="Pièce d'identité (verso)",
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="id_front",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="applications/id/%Y/%m/",
                verbose_name="Pièce d'identité (recto)",
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="photo",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="applications/photos/%Y/%m/",
                verbose_name="Photo passeport",
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="supporting_documents",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="applications/documents/%Y/%m/",
                verbose_name="Documents justificatifs",
            ),
        ),
    ]
