# Generated by Django 5.2.17 on 2026-08-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_alter_associationsettings_collective_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="founder_title",
            field=models.CharField(
                blank=True,
                help_text="Ex. : Président fondateur, Initiateur, Membre fondateur...",
                max_length=120,
                verbose_name="Titre de fondateur",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="is_founder",
            field=models.BooleanField(default=False, verbose_name="Membre fondateur"),
        ),
        migrations.AddField(
            model_name="member",
            name="is_initiator",
            field=models.BooleanField(
                default=False, verbose_name="Initiateur / 1er président"
            ),
        ),
    ]
